stages:
  - preparation
  - building
  - testing
  - security

image: edbizarro/gitlab-ci-pipeline-php:7.4-alpine

# Variables
variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: mysql_user
  MYSQL_PASSWORD: mysql_password
  MYSQL_DATABASE: mysql_db
  DB_HOST: mysql

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

composer:
  stage: preparation
  only:
    - master
  script:
    - php -v
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp "$ENV" .env
    - php artisan key:generate
  artifacts:
    paths:
      - vendor/
      - "$ENV"
    expire_in: 1 days
    when: always
  cache:
    paths:
      - vendor/

yarn:
  stage: preparation
  only:
    - master
  script:
    - yarn --version
    - yarn install --pure-lockfile
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 days
    when: always
  cache:
    paths:
      - node_modules/

migration:
  stage: building
  only:
    - master
  services:
    - name: mysql:5.7
  dependencies:
    - composer
  script:
    - mysql --version
    - cp "$ENV" .env
    - php artisan migrate:fresh --seed
  artifacts:
    paths:
      - storage/logs
    expire_in: 1 days
    when: always

phpunit:
  stage: testing
  only:
    - master
  services:
    - name: mysql:5.7
  dependencies:
    - composer
    - migration
  script:
    - php -v
    - cp "$ENV" .env
    - ./vendor/bin/phpunit --colors=never
  allow_failure: true
  artifacts:
    paths:
      - ./storage/logs
    expire_in: 1 days
    when: on_failure

sensiolabs:
  stage: security
  only:
    - master

  script:
    - test -d security-checker || git clone https://github.com/sensiolabs/security-checker.git
    - cd security-checker
    - composer install
    - php security-checker security:check ../composer.lock
  dependencies: []
  cache:
    paths:
      - security-checker/
